### ISSUE TITLE
template xml.j2-file examples missing

### ISSUE THREAD

**Issue by sjjamsa** [guidugli/ansible-role-kvm#1]
Dear @guidugli,

I was browsing for a role to install kvm, and your role looks like up-to date and comprehensive. I didn't test it yet. 

To me, it seems that the example jinja templates for xml.j2 files are missing. In [defaults/main.yml](https://github.com/guidugli/ansible-role-kvm/blob/v1.0.3/defaults/main.yml) one can see many commented out references to .xml.j2 files.

Could you share examples?

Thanks!

 \- Simppa -

**Comment by guidugli** [comment]
Hi @sjjamsa ,

Thank you for your suggestion, I will update the readme page.

The VM templates are the VM XML definition files located /etc/libvirt/qemu. 
The Network templates are the Network XML definition files located at /etc/libvirt/qemu/networks.
And Storage (pools) is similar, the template is equal to the storage XML definition files located at /etc/libvirt/storage.

The way I use it, I create a templates directory with this structure:
templates/vms
templates/pools
templates/networks

Then you place the template files in the corresponding folder. The files should have .j2 extension. I used templates instead of files so users can use variable substitution, if necessary.
